// The demo collector's collection (ADR-016).
//
// GENERATED by scripts/export-demo-fixtures.ts from the source demo account, then
// committed. Do not hand-edit — re-run `npm run db:export-demo` to refresh it.
// It is the shop-window collection a visitor sees on the public demo tenant,
// loaded through the domain services by scripts/seed-demo.ts.
//
// The coin photographs in demo-assets/ are the account owner's own images — see
// demo-assets/LICENSES.md.

export type DemoValuation = {
  amount: number;
  currency: string;
  valuedAt: string;
  source?: string;
  sourceUrl?: string;
};

export type DemoCoin = {
  // Coins have no name column: the title is derived from these attributes by
  // formatCoinTitle (ADR-006).
  attributes: Record<string, unknown>;
  /** Files in demo-assets/, in carousel order (obverse first). */
  images?: string[];
  /** Auction invoice: a generated PDF receipt. */
  invoice?: { filename: string; house: string; lot: string; date: string; total: string };
  valuations?: DemoValuation[];
};

export type DemoCollection = { name: string; coins: DemoCoin[] };

export const DEMO_BASE_CURRENCY = "EUR";

export const DEMO_COLLECTIONS: DemoCollection[] = [
  {
    name: "Roman Republic, Imperatorial & Empire",
    coins: [
      {
        // Roman Republic. Brutus (42 BC), Rome
        attributes: {
          issuingAuthority: "Brutus",
          category: "Roman Republic",
          denomination: "Denarius",
          mint: "Rome",
          metal: "Silver",
          grade: "AU",
          obverseDescription: "Bare head of Brutus right; above and before, inscription; behind, moneyer mark, within a border of dots.\nLegend: BRVT IMP - L•PLAET•CES",
          reverseDescription: "Pileus between two daggers; below, inscription. Border of dots.\nLegend: EID•MAR",
          observations: "This coin is of particular interest as it combines on obverse the only known portrait of Brutus on a coin and on reverse an unabashed celebration of the assassination of Julius Caesar.",
          catalogueReferences: "RRC# 508/3, CRR# 1301, RSC# 15, RCV I# 1439, BMC RR# 68-70, Sear Imperators# 216, Hunt# 119, Vagi# 95, Kent & Hirmer# 98, FFC# 1",
          pedigree: "Classical Numismatic Group, Feature Auction 10, lot 333 (15/02/2003)\nNumismatica Ars Classica, Auction 1, lot 150 (25/05/1980)",
          auctionHouse: "Numismatica Ars Classica",
          auctionName: "Auction 25",
          auctionLot: "459",
          yearFrom: -42,
          yearTo: -42,
          weight: 3.72,
          diameter: 18,
          auctionDate: "2020-12-19",
          hammerPrice: 3000,
          auctionPremium: 600,
          shippingCost: 50,
          taxCost: 300,
          priceCurrency: "EUR",
        },
        images: ["brutus-denarius-obverse.jpg", "brutus-denarius-reverse.jpg"],
      },
      {
        // Roman Empire. Hadrian (117 AD – 138 AD), Rome
        attributes: {
          issuingAuthority: "Hadrian",
          category: "Roman Empire",
          denomination: "Aureus",
          mint: "Rome",
          metal: "Gold",
          grade: "MS",
          obverseDescription: "Head of Hadrian to the left",
          reverseDescription: "Hispania reclining left on rocks, holding branch; to left, rabbit",
          observations: "In mint state and the best coin for the type!",
          pedigree: "Gorny & Mosch, Auciton 250, lot 555 (25/10/2012)",
          auctionHouse: "Numismatica Ars Classica",
          auctionName: "Summer Auction 30",
          auctionLot: "300",
          yearFrom: 117,
          yearTo: 138,
          weight: 7.3,
          diameter: 20,
          auctionDate: "2022-02-07",
          hammerPrice: 5000,
          auctionPremium: 1000,
          shippingCost: 50,
          taxCost: 500,
          priceCurrency: "EUR",
        },
        images: ["hadrian-aureus-obverse.jpg", "hadrian-aureus-reverse.jpg"],
      },
      {
        // Roman Republic. Mark Antony & Cleopatra (36 BC), Antioch
        attributes: {
          issuingAuthority: "Mark Antony & Cleopatra",
          category: "Roman Republic",
          denomination: "Tetradrachm",
          mint: "Antioch",
          metal: "Silver",
          grade: "EF",
          obverseDescription: "Diademed bust of Queen Cleopatra VII facing right, with hair in cornrows, wearing beaded earrings, necklace, and embroidered dress. Legend: ΒΑϹΙΛΙϹϹΑ ΚΛƐΟΠΑΤΡΑ ΘƐΑ ΝƐWΤƐΡΑ",
          reverseDescription: "Bare head of Marc Antony right. Legend: ΑΝΤWΝΙΟϹ ΑΥΤΟΚΡΑΤWΡ ΤΡΙΤΟΝ ΤΡΙWΝ ΑΝΔΡWΝ",
          observations: "One of the finest among this rare, spectacular and very historically important coin!",
          catalogueReferences: "RPC Online I# 4094, McAlee# 174, Prieur# 27, HGC 9# 1361, BMC Greek# 53",
          auctionHouse: "Heritage Auctions",
          auctionName: "Auction 30",
          auctionLot: "3215",
          yearFrom: -36,
          weight: 13.74,
          diameter: 26,
          auctionDate: "2026-02-11",
          hammerPrice: 2000,
          auctionPremium: 400,
          shippingCost: 50,
          taxCost: 200,
          priceCurrency: "EUR",
        },
        images: ["mark-antony-cleopatra-tetradrachm-obverse.jpg", "mark-antony-cleopatra-tetradrachm-reverse.jpg"],
      },
    ],
  },
  {
    name: "Spanish Empire",
    coins: [
      {
        // Spanish Empire. Carlos III (1769 AD), Santiago
        attributes: {
          issuingAuthority: "Carlos III",
          category: "Spanish Empire",
          denomination: "8 Escudos",
          mint: "Santiago",
          metal: "Gold",
          grade: "AU",
          obverseDescription: "'Cara de rata' (rat nose) bust of king Carlos to the right",
          reverseDescription: "Crowned Spanish Royal Arms surrounded by the Order of the Golden Fleece chain, flanked by the coin's value and mint markings.",
          observations: "In numismatics, the expression \"rat nose\" refers to a famous bust of King Charles III minted between 1762 and 1772 on gold and silver coins. Designed by the engraver Tomás Francisco Prieto, the nickname highlights the monarch's sharp features and prominent nose, and it is now one of the most coveted pieces among collectors.",
          auctionHouse: "Aureo y Calicó",
          auctionName: "Subasta especial 15",
          auctionLot: "225",
          yearFrom: 1769,
          yearTo: 1769,
          weight: 27,
          diameter: 30,
          auctionDate: "2024-05-02",
          hammerPrice: 2500,
          auctionPremium: 500,
          shippingCost: 30,
          taxCost: 0,
          priceCurrency: "EUR",
        },
        images: ["carlos-iii-8-escudos-obverse.jpg", "carlos-iii-8-escudos-reverse.jpg"],
      },
      {
        // Spanish Empire. Felipe IV (1637 AD), Segovia
        attributes: {
          issuingAuthority: "Felipe IV",
          category: "Spanish Empire",
          denomination: "8 Escudos",
          mint: "Segovia",
          metal: "Gold",
          grade: "MS",
          obverseDescription: "Crowned coat of arms of Spain with Portugal arms. Legend: PHILIPPVS ❀ IIII ❀ D ❀ G\nR VIII",
          reverseDescription: "Cross in quatrefoil. Legend: HISPANIARVM ❀ REX ❀ 1637 ❀",
          observations: "Impressive coin, top pop!",
          pedigree: "Aureo & Calicó, Auction 25, lot 2022 (15/10/2008)",
          auctionHouse: "Aureo & Calicó",
          auctionName: "Auction 50",
          auctionLot: "300",
          yearFrom: 1637,
          weight: 27,
          diameter: 30,
          auctionDate: "2020-04-11",
          hammerPrice: 3500,
          auctionPremium: 700,
          shippingCost: 100,
          taxCost: 0,
          priceCurrency: "EUR",
        },
        images: ["felipe-iv-8-escudos-obverse.jpg", "felipe-iv-8-escudos-reverse.jpg"],
      },
      {
        // Spanish Empire. Ferdinand VII (1808 AD), Madrid
        attributes: {
          issuingAuthority: "Ferdinand VII",
          category: "Spanish Empire",
          denomination: "2 Reales",
          mint: "Madrid",
          metal: "Silver",
          grade: "MS",
          obverseDescription: "Crowned oval coat of arms of Spain. Legend: FERDINAND · VII · D · G · HISPANIAN · ET IND · REX",
          reverseDescription: "Monogram of king Ferdinand VII, radiant star above and olive branches below. Legend:  ACCLAMATIO AVGVSTA MATR · D · 24 AVG · AN · 1808.",
          observations: "Very rare proclamation medal!",
          pedigree: "Soler & Llach, Auction 100, lot 200 (10/12/1995)",
          auctionHouse: "Sedwick & Associates",
          auctionName: "Auction 5",
          auctionLot: "450",
          yearFrom: 1808,
          weight: 5.9,
          diameter: 26,
          auctionDate: "2021-05-02",
          hammerPrice: 5000,
          auctionPremium: 1000,
          shippingCost: 50,
          taxCost: 500,
          priceCurrency: "EUR",
        },
        images: ["ferdinand-vii-2-reales-obverse.jpg", "ferdinand-vii-2-reales-reverse.jpg"],
      },
    ],
  },
];
